config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :cocktails, only: [ :new, :edit, :create, :index, :show, :destroy ] do

    resources :doses, only: [:create]
  end

  resources :doses, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_rich_text :rich_body

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses, dependent: :destroy

  ## Validations
  validates :name, presence: true, uniqueness: true

  has_one_attached :photo

  accepts_nested_attributes_for :ingredients, :doses


  # def dose_description=(description)
  #   @dose.description = description
  # end

  # def dose_description
  #   @dose.description
  # end
end

app/models/dose.rb
class Dose < ApplicationRecord

  belongs_to :cocktail
  belongs_to :ingredient
  ## Validations
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord

  has_many :doses
  has_many :cocktails, through: :doses

  # validates
  validates :name, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:id])
    @doses = Dose.where(cocktail_id: params[:id])
    # @ingredient = ""

  end
  #CREATE
  def new
    @cocktail = Cocktail.new # needed to instantiate the form_for
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    # raise
    if @cocktail.save
      # no need for app/views/cocktails/create.html.erb
      redirect_to cocktail_path(@cocktail) # cocktails ( pural will take u to All )
    else
      render :new
    end
  end

  # UPDATE
  def edit
    @cocktails = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    if @cocktail.update(cocktail_params)
      # no need for app/views/cocktails/update.html.erb
      redirect_to cocktail_path(@cocktail)
    else
      render :edit
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    # no need for app/views/cocktails/destroy.html.erb
    redirect_to cocktails_path
  end
  private

  def has_doses?
    @cocktail.dose_ids.last = nil
    return '<%= link_to "Add Dose", new_cocktail_dose_path(@cocktail) , class: "btn card-link " %>'
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :ingredient, :photo, :image_scr, :rich_body)
    # params.require(:dose).permit(:ingredient)
  end

  def find_cocktail_params
    @cocktail = Cocktail.find(params[:id])
  end


end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  # def new
  #   # we need @cocktail in our `simple_form_for`

  #   @cocktail = Cocktail.find(params[:cocktail_id])
  #   @dose = Dose.new
  #   # raise
  # end

  def create

    # @dose = Dose.new(dose_params)
    #  "dose"=>{"description"=>"1oz", "ingredient_id"=>["1", "2"]},
    # "commit"=>"Submit Dose",
    #{}"cocktail_id"=>"1"}
    # we need `restaurant_id` to associate dose with corresponding restaurant

    @cocktail = Cocktail.find(params[:cocktail_id])
    ing_ids = params[:dose][:ingredient_id]

    #array empty or desc empty ?
    if ing_ids.nil? || params[:dose][:description].empty?
      redirect_to new_cocktail_dose_path(@cocktail)
    else
      ing_ids.each do |ing_id|
        # @ing = Ingredient.find(ing_id)
        @dose = Dose.new(
          description: (params[:dose][:description]),
          cocktail_id: (params[:cocktail_id]),
          ingredient_id: ing_id
        )
        # @dose.cocktail = @cocktail
        if @dose.valid?
          @dose.save
        else
          render :new
        end
      end
      redirect_to cocktail_path(@cocktail)
    end
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.where(cocktail_id: params[:id])
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end
  private

  def dose_params
    params.require(:dose).permit(:ingredient_id, :description, :cocktail_id)
    # params.require(:ingredient).permit(:ingredient_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/cocktails/edit.html.erb
<div class="container py-3">
    <h1>Edit
        <b>
            <%= @cocktails.name %></b>
    </h1>
    <%= simple_form_for [ @cocktails ] do |f| %>
    <%= f.input :name %>
    <%= f.submit "Submit Drink", class: "btn btn-primary" %>
    <% end %>
</div>

app/views/cocktails/index.html.erb
<!-- <div id="top" class="container">
    <h1 id="top" class="text-center py-5">Get Drunk In</h1>
    <div id="flipdown" class="flipdown mx-auto"></div>
</div> -->
<div id="main" class="container mx-auto py-3">
  <!-- style="display: none;" -->
  <div class="row mx-auto justify-content-around py-5">
    <% @cocktails.each do |cocktail| %>
      <div class="col-lg-4 col-md-6 col-sm-12 py-1">
        <div class="card" style="width: 100%;">
          <% cocktail.photo.attached? ? @image = "//res.cloudinary.com/matoni109/image/upload/#{cocktail.photo.key}": @image = cocktail.image_scr %>
          <img class="card-i.namg-top" src="<%= @image %>" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">
              <%= cocktail.name %>
            </h5>
            <p class="card-text">
              <i class="fas fa-dollar-sign"></i>
              <%= cocktail.id %>
            </p>
            <%= link_to "More Info", cocktail_path(cocktail) , class: "btn btn-link" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container py-3">
    <h1>Add a New Drink</h1>
    <%= simple_form_for [ @cocktail ] do |f| %>
    <%= f.input :name %>
    <!--  <%= f.input :image_scr %> -->
    <%= f.input :photo, as: :file %>
    <%= f.rich_text_area :rich_body %>
    <%= f.submit "Submit Drink", class: "btn btn-primary my-2" %>
    <% end %>
</div>

app/views/cocktails/show.html.erb
<% @cocktail.photo.attached? ? @image = "//res.cloudinary.com/matoni109/image/upload/#{@cocktail.photo.key}": @image = @cocktail.image_scr %>
<div class="background my-2" style="height: 50vh; background-image: url('<%= @image %>')"></div>
<div class="container">
    <div class="row">
        <div class="col-md-8 col-sm-12 margin-top-negative">
            <div class="card py-3 my-3" style="width: 100%;">
                <div class="card-body ">
                    <h2 class="card-title">
                        <%= @cocktail.name %>
                    </h2>
                    <h6 class="card-subtitle mb-2 text-muted">
                        <%= @cocktail.name %>
                    </h6>
                </div>
            </div>
            <div class="card" style="width: 100%;">
                <div class="card-body">
                    <h2 class="card-title">
                        <%= @cocktail.name %> Info</h2>
                    <h6 class="card-subtitle mb-2 text-muted"></h6>
                    <p class="card-text">
                        <h5>Ingredients</h5>
                        <!-- @cocktail.doses[0].ingredient[:name] -->
                        <ul>
                            <% @cocktail.doses.each do |dose|%>
                            <li>
                                <%= dose.ingredient[:name] %>
                                <b>
                                    <%= dose.description %></b>
                                <%= link_to "Remove Dose", dose_path(dose),method: :delete, data: { confirm: "Are you sure?" }, class: "btn card-link" %>
                            </li>
                            <% end %>
                        </ul>
                        <%= link_to "Edit Name", edit_cocktail_path(@cocktail) , class: "btn card-link " %>
                        <%= link_to "Remove Drink", cocktail_path(@cocktail),method: :delete, data: { confirm: "Are you sure?" }, class: "btn card-link" %>
                        <!--   <% if @cocktail.dose_ids.last == nil %>
                        <%#= link_to "Add Dose", new_cocktail_dose_path(@cocktail) , class: "btn card-link " %>
                        <% else %> -->
                        <%= link_to "Remove Last Dose", dose_path(@cocktail.dose_ids.last),method: :delete, data: { confirm: "Are you sure?" }, class: "btn card-link" %>
                        <!--   <%#= link_to "Add Dose", new_cocktail_dose_path(@cocktail) , class: "btn card-link " %>
                        <% end %> -->
                </div>
            </div>
            <div class="card my-5" style="width: 100%;">
                <div class="card-body">
                    <h2 class="card-title">
                        <%= @cocktail.name %> Info</h2>
                    <h6 class="card-subtitle mb-2 text-muted"></h6>
                    <p class="card-text">
                        <h1>Add a Dose to <b>
                                <%= @cocktail.name %></b> </h1>
                        <%= simple_form_for [ @cocktail, @dose] do |f| %>
                        <%= f.input :description %>
                        <%= f.association :ingredient, input_html: { multiple: true, class: "multiple-select" }, include_hidden: false %>
                        <%= f.submit "Submit Dose", class: "btn btn-primary" %>
                        <% end %>
                </div>
            </div>
        </div>
        <div class="col-md-4 col-sm-12 margin-top-negative">
            <div class="card py-3 my-3" style="width: 100%;">
                <div class="card-body">
                    <h2 class="card-title">
                        <%= @cocktail.name %> Method</h2>
                    <h6 class="card-subtitle mb-2 text-muted"></h6>
                    <p class="card-text">
                        <%= @cocktail.description %>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/doses/index.html.erb
<h1>Doses#index</h1>
<p>Find me in app/views/doses/index.html.erb</p>

app/views/doses/new.html.erb
<div class="container py-3">
    <h1>Add a Dose to <b>
            <%= @cocktail.name %></b> </h1>
    <%= simple_form_for [ @cocktail, @dose ] do |f| %>
    <%= f.input :description %>
    <%= f.association :ingredient, input_html: { multiple: true, class: "multiple-select" }, include_hidden: false %>
    <%= f.submit "Submit Dose", class: "btn btn-primary" %>
    <% end %>
</div>

app/views/doses/show.html.erb
<h1>Doses#show</h1>
<p>Find me in app/views/doses/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,400,900" rel="stylesheet">
    <script defer type="text/javascript" src="https://pbutcher.uk/flipdown/js/flipdown/flipdown.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', defer: true, 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <div class="navbar-lewagon d-flex justify-content-between p-2">
        <%= link_to"Simple Get Drunk!", cocktails_path, class: "my-auto " %>
        <%= link_to "Add A Drink", new_cocktail_path , class: "btn btn-outline-primary" %>
    </div>
    <%= yield %>
</body>

</html>